package com.yp.pm.kp.be.query;

public interface KeplerAccountQuery {

    String GET_ACCOUNT_ID_BY_NAME = "SELECT ACCOUNT_ID FROM PM_ACCOUNT WHERE CLIENT_NAME = ?";
    String GET_ACTIVE_ACCOUNT_ID_BY_NAME = "SELECT ACCOUNT_ID, FINANCIAL_STATUS FROM PM_ACCOUNT WHERE ACCOUNT_STATUS = ? AND CLIENT_NAME = ?";
}